#!/bin/sh
V="-v"

## Script to update web resources. Usually invoked as ./sync-files -v
## Needs to be run from the dir containing the COMP101 notes

## Things to update
YEAR=2013
COMP101HOME=$HOME/Teach/COMP10120/COMP101
COMP101HOME=.
USR=graham

while getopts qnu: c
do
    case $c in
	v) V=${V}v;;
	q) V=-q;;
	n) V=${V}n;;
	u) USR=$OPTARG;;
    esac
done

if [ X$V = X-q ]
then
   :
else
    echo `basename $0`
fi

##### update course material on waldorf
if [ X$V = X-q ]
then
   :
else
    echo 'Updating waldorf'
fi

## Use sonofis7 so can update from outside School

for file in index.html 101labs.pdf welcome.pdf rpi1.pdf rpi2.pdf desktop1.pdf desktop2.pdf desktop3.pdf desktop4.pdf latex.pdf desktop5.pdf appendix.pdf
do 
echo $file 
done | rsync -a  $V  -e  'ssh -p1001' --files-from=- . $USR@sonofis7.cs.man.ac.uk:/www/virtualHosts/studentnet/ugt/$YEAR/COMP10120/labscripts


for file in mutt-template Advent.z5 quake3.tar.gz mrnoodle.tar.gz
do 
echo $file
done | rsync -a  $V  -e  'ssh -p1001' --files-from=- files $USR@sonofis7.cs.man.ac.uk:/www/virtualHosts/studentnet/ugt/$YEAR/COMP10120/files/


exit
