#!/bin/bash

directory="$1"

(cat << .
\\documentclass[10pt]{article}
\\usepackage{a4-mancs}
\\usepackage{longtable}
\\begin{document}
\\begin{center}
\\Large
\\textbf{Directory listing for `pwd`} \\\\[.3em]
\\small
.

cat << "."
\end{center}
\small
.

cat << "."
\begin{longtable}{|l|l|l|l|l|l|l|l|l|} \hline
Perms & L & Owner & Group & Size & M & D & Y/T & Name \\ \hline
\endhead
.

ls -l $directory | tail --lines=+2 \
| sed -e 's,_,\\_,g' \
      -e 's, -> ,->,g' \
      -e 's,  *, \& ,g' \
      -e 's,>,\\textgreater ,g' \
      -e 's,$, \\\\,'

cat << "."
\hline
\end{longtable}
\end{document}
.
) > ls.tex

viewer=acroread4
viewer=evince

pdflatex ls.tex && pdflatex ls.tex && $viewer ls.pdf
